"""empty message

Revision ID: 1254d506c339
Revises: f7651ea9c18d
Create Date: 2023-11-22 08:54:25.329648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1254d506c339'
down_revision = 'f7651ea9c18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lhomework', schema=None) as batch_op:
        batch_op.alter_column('duedate',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lhomework', schema=None) as batch_op:
        batch_op.alter_column('duedate',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
