"""empty message

Revision ID: 2b5b2f3b0546
Revises: e5c7aed886a1
Create Date: 2023-11-19 21:49:13.940644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b5b2f3b0546'
down_revision = 'e5c7aed886a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ls')
    with op.batch_alter_table('shomework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shomework', schema=None) as batch_op:
        batch_op.drop_column('state')

    op.create_table('ls',
    sa.Column('lid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('state', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('lid', 'sid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
