"""empty message

Revision ID: 56e7ef091f5b
Revises: 2b5b2f3b0546
Create Date: 2023-11-19 22:25:57.474709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e7ef091f5b'
down_revision = '2b5b2f3b0546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shomework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lid', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shomework', schema=None) as batch_op:
        batch_op.drop_column('lid')

    # ### end Alembic commands ###
