"""empty message

Revision ID: 92685fc6bf4a
Revises: c31eea54470c
Create Date: 2023-12-22 08:52:10.326765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92685fc6bf4a'
down_revision = 'c31eea54470c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shomework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grade2', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shomework', schema=None) as batch_op:
        batch_op.drop_column('grade2')
        batch_op.drop_column('grade1')

    # ### end Alembic commands ###
