"""empty message

Revision ID: c31eea54470c
Revises: 1254d506c339
Create Date: 2023-12-18 09:07:13.158922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31eea54470c'
down_revision = '1254d506c339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lhomework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename1', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('filename2', sa.String(length=1000), nullable=True))

    with op.batch_alter_table('shomework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shomework', schema=None) as batch_op:
        batch_op.drop_column('filename')

    with op.batch_alter_table('lhomework', schema=None) as batch_op:
        batch_op.drop_column('filename2')
        batch_op.drop_column('filename1')

    # ### end Alembic commands ###
