"""empty message

Revision ID: e5c7aed886a1
Revises: 65886a15ea83
Create Date: 2023-11-19 19:00:13.972215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c7aed886a1'
down_revision = '65886a15ea83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shomework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shomework', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
