"""empty message

Revision ID: f7651ea9c18d
Revises: 56e7ef091f5b
Create Date: 2023-11-22 08:50:34.051016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7651ea9c18d'
down_revision = '56e7ef091f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lhomework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('evaluation', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lhomework', schema=None) as batch_op:
        batch_op.drop_column('evaluation')
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
